// @ts-check
// Sidebars are autogenerated from the folder tree under /docs.
// Each institution gets its own sidebar so the navbar tabs are independent.
// To reorder/rename, drop `_category_.json` files inside the relevant folder.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  ioe:   [{ type: 'autogenerated', dirName: 'ioe' }],
  ctevt: [{ type: 'autogenerated', dirName: 'ctevt' }],
  tu:    [{ type: 'autogenerated', dirName: 'tu' }],
};

module.exports = sidebars;
